apiVersion: v1
kind: Service
metadata:
  labels:
    app: datadog
  name: datadog-scheduler-metrics
spec:
  ports:
  - name: agentport
    port: 10259
    protocol: TCP
    targetPort: 10259
  selector:
    app: datadog-master-node-pause
  sessionAffinity: None
  type: ClusterIP