apiVersion: v1
kind: Service
metadata:
  annotations:
    ad.datadoghq.com/endpoints.check_names: '["kube_scheduler"]'
    ad.datadoghq.com/endpoints.init_configs: '[{}]'
    ad.datadoghq.com/endpoints.instances: '[{"prometheus_url":"https://%%host%%:10259/metrics",
      "bearer_token_auth": true, "ssl_ca_cert": false}]'
    ad.datadoghq.com/service.check_names: '[""]'
    ad.datadoghq.com/service.init_configs: '[{}]'
    ad.datadoghq.com/service.instances: '[{}]'
  labels:
    app: datadog
  name: datadog-scheduler-metrics
spec:
  ports:
  - name: agentport
    port: 10259
    protocol: TCP
    targetPort: 10259
  selector:
    app: datadog-master-node-pause
  sessionAffinity: None
  type: ClusterIP